### ISSUE TITLE
Compilatio Error.

### ISSUE THREAD

**Issue by Itz-Verma** [Whiax/NeuralNetworkCpp#3]
Hey!
I am on kali-linux Desktop.
I cloned this repo and tried to compiled it.
There a lot of bugs(in my view).

For instance:
In file **src/neral/layer.h**  enum ActivationFunction is only declared and not defined. I noticed It is defined in **src/neural/neuron.h** but it gave error.

I made a new  header file **activationfunction.h** in **src/neural** and defined the enum in it and then include it in both layer.h and neuron.h.
It worked file after doing other bug fixing.

was it compiled on your pc?
I just want to know.

If you want me to mention all bug I will do it.

**Comment by Whiax** [comment]
Hi, I developed the code using Visual Studio in Windows. It seems that it simplifies the code but it makes it less compatible if you want to compile it by yourself on Linux, sorry for that. I'll try to update it when I have the time.

**Comment by Itz-Verma** [comment]
Well Ok then.
